// Next
import type { Metadata } from "next";
// Google Fonts
import { Almarai } from "next/font/google";
// Components 
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
// Shadcn UI
import { ScrollArea } from "@/components/ui/scroll-area"
// Style
import "./globals.css";


const almarai = Almarai({
  variable: "--font-almarai",
  subsets: ["arabic"],
  weight: "300",
  display: "swap",
  fallback: ["sans-serif"],
});


export const metadata: Metadata = {
  title: "حبار الذكية للدعاية و الأعلان",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${almarai.variable} antialiased`}
      >
        <div>
          <div className="h-[126px]"></div>
          <Header />
          <div className="flex flex-row-reverse justify-end bg-[#F4F7FC] h-96 overflow-hidden dashboard-view">
            <Navbar />
            <ScrollArea className="flex-[4]">
              {children}
            </ScrollArea>
          </div>
        </div>
      </body>
    </html>
  );
}
